repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks

  - repo: local
    hooks:
      - id: pet-validate
        name: pet validate
        entry: pet validate
        language: system
        pass_filenames: false
        files: ^doc/product/
